/**
 * Automation Test Cases — generate Playwright + Java automation code.
 */

import { useEffect, useState } from "react";
import { useParams } from "react-router";
import { useModStore, genId } from "../context";
import type { AutomationTestCase } from "../lib/types";
import { Bug, Download } from "lucide-react";

export default function ModAutomationCases() {
  const { projectId } = useParams<{ projectId: string }>();
  const { state, dispatch } = useModStore();
  const [viewingId, setViewingId] = useState<string | null>(null);

  useEffect(() => {
    if (projectId) dispatch({ type: "SET_CURRENT_PROJECT", projectId });
  }, [projectId, dispatch]);

  const project = state.projects.find((p) => p.id === projectId);
  if (!project) return <div className="flex items-center justify-center h-64 text-xs text-muted-foreground">Project not found.</div>;

  const cases = Object.values(state.automationTestCases).filter((c) => c.projectId === project!.id);
  const manualCases = Object.values(state.testCases).filter((tc) => tc.projectId === project!.id);

  function generateAutomation() {
    const newCases: AutomationTestCase[] = [];
    manualCases.forEach((tc) => {
      const className = tc.testcaseId.replace(/-/g, "") + "Test";
      const javaCode = `package com.modernization.test;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.WebDriver;

/**
 * Test Case: ${tc.testcaseId}
 * Requirement: ${tc.requirement}
 * Generated by MIPTE Client-Side Platform
 */
public class ${className} {

    @Test
    public void test_${tc.testcaseId.toLowerCase().replace(/-/g, "_")}() {
        // TODO: Set up WebDriver
        // WebDriver driver = WebDriverFactory.create();

        // TODO: Execute job: ${tc.steps.split("\n")[0] ?? "Execute functionality"}

        // TODO: Validate expected result
        // ${tc.expectedResult}

        // TODO: Capture evidence screenshot
        // Screenshot.capture(driver, "${tc.testcaseId}_result.png");

        // TODO: Assert expected behavior
        // Assertions.assertEquals(expected, actual);
        Assertions.fail("TODO: Implement test automation");
    }
}`;
      newCases.push({
        id: genId(), projectId: project!.id, testcaseId: tc.testcaseId,
        className, methodName: `test_${tc.testcaseId.toLowerCase().replace(/-/g, "_")}`,
        javaCode, requirement: tc.requirement, status: "GENERATED", createdAt: Date.now(),
      });
    });
    if (newCases.length > 0) {
      dispatch({ type: "SET_AUTOMATION_TEST_CASES", cases: newCases });
    }
  }

  function exportJava(c: AutomationTestCase) {
    const blob = new Blob([c.javaCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${c.className}.java`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  const viewing = viewingId ? cases.find((c) => c.id === viewingId) : null;

  return (
    <div className="max-w-4xl mx-auto px-6 py-10 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-semibold tracking-tight">Automation Test Cases</h1>
          <p className="mt-1 text-xs text-muted-foreground">{cases.length} Java/Selenium test cases</p>
        </div>
        <button onClick={generateAutomation}
          className="inline-flex items-center gap-1.5 rounded-md bg-foreground px-3 py-1.5 text-[11px] font-medium text-background hover:opacity-90">
          <Bug className="size-3" /> Generate from Manual Cases
        </button>
      </div>

      {cases.length === 0 ? (
        <div className="rounded-lg border border-border border-dashed bg-card p-10 text-center">
          <Bug className="mx-auto size-6 text-muted-foreground/40" />
          <p className="mt-2 text-xs text-muted-foreground">
            {manualCases.length === 0
              ? "Create manual test cases first, then generate automation."
              : "Generate automation test cases from your manual test cases."}
          </p>
        </div>
      ) : (
        <div className="space-y-2">
          {cases.map((c) => (
            <div key={c.id} className="flex items-center justify-between rounded-lg border border-border bg-card px-4 py-3">
              <div className="min-w-0 cursor-pointer" onClick={() => setViewingId(c.id)}>
                <p className="text-xs font-medium">{c.className}</p>
                <p className="text-[10px] text-muted-foreground mt-0.5">{c.requirement}</p>
              </div>
              <div className="flex items-center gap-2 shrink-0 ml-3">
                <span className="text-[9px] px-1.5 py-0.5 rounded bg-muted text-muted-foreground">{c.status}</span>
                <button onClick={() => exportJava(c)} className="p-1.5 rounded text-muted-foreground hover:text-foreground hover:bg-muted transition-colors" title="Export Java">
                  <Download className="size-3" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Code Viewer Modal */}
      {viewing && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setViewingId(null)}>
          <div className="w-full max-w-3xl max-h-[80vh] bg-card rounded-lg border border-border shadow-xl overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
              <p className="text-xs font-medium">{viewing.className}.java</p>
              <button onClick={() => setViewingId(null)} className="text-[10px] text-muted-foreground hover:text-foreground">Close</button>
            </div>
            <pre className="flex-1 overflow-auto p-4 text-[11px] leading-5 font-mono whitespace-pre-wrap">{viewing.javaCode}</pre>
          </div>
        </div>
      )}
    </div>
  );
}
